runtime: nodejs12

instance_class: F4_1G

automatic_scaling:
 # target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  # max_concurrent_requests: 50


handlers:
# Serve static files
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
#  handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
